export const DEPARTMENTS_LIST = [
    'Administration',
    'Revenue',
    'Accounts',
    'Town Planning',
    'Engineering',
    'Public Health',
    'UPA Cell',
    'GMC Infrastructure',
    'Water Supply',
];


export const ADMINISTRATION_DEPARTMENT_DESIGNATIONS = [
    'Manager',
    'Superintendent',
    'Senior Assistant, C1',
    'Senior Assistant, C5',
    'Junior Assistant, C8',
    'Junior Assistant, C9',
    'Typist, C10',
    'Senior Assistant, D1',
    'Record Assistant, D2',
    'Record Assistant, D7 I/c',
    'Revenue Officer - I',
    'Revenue Officer - II',
    'Revenue Officer - III',
    'Revenue Officer - IV',
    'Revenue Inspector - I',
    'Revenue Inspector - II',
    'Revenue Inspector - III',
    'Revenue Inspector - IV',
    'Revenue Inspector - V',
    'Revenue Inspector - VI',
    'Revenue Inspector - VII',
    'Revenue Inspector - VIII',
    'Revenue Inspector - IX',
];